# Generated by Django 2.2.5 on 2019-12-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191010_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата создания'),
        ),
    ]
